### ISSUE TITLE
Problem with 2024.4.1 - Unable to install package matplotlib

### ISSUE THREAD

**Issue by cortado** [tmjo/ha-norwegiantide#9] opened 2024-04-07 17:31 UTC
Running HAOS on RPi4, latest everything. 

Log:
Logger: homeassistant.util.package
Kilde: util/package.py:123
Førs oppstått: 14:27:05 (1 hendelser)
Sist logget: 14:27:05

Unable to install package matplotlib>=3.3.3: error: subprocess-exited-with-error × pip subprocess to install build dependencies did not run successfully. │ exit code: 1 ╰─> [80 lines of output] Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/, https://wheels.home-assistant.io/musllinux-index/ Collecting certifi>=2020.06.20 Downloading https://wheels.home-assistant.io/musllinux-index/certifi-2024.2.2-py3-none-any.whl (163 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 728.0 kB/s eta 0:00:00 Collecting pybind11>=2.6 Downloading pybind11-2.12.0-py3-none-any.whl.metadata (9.5 kB) Collecting setuptools>=64 Downloading https://wheels.home-assistant.io/musllinux-index/setuptools-69.2.0-py3-none-any.whl (821 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 821.5/821.5 kB 795.0 kB/s eta 0:00:00 Collecting setuptools_scm>=7 Downloading setuptools_scm-8.0.4-py3-none-any.whl.metadata (6.4 kB) Collecting numpy<2.3,>=2.0.0rc1 Downloading numpy-2.0.0rc1.tar.gz (18.3 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 352.2 kB/s eta 0:00:00 Installing build dependencies: started Installing build dependencies: still running... Installing build dependencies: finished with status 'done' Getting requirements to build wheel: started Getting requirements to build wheel: finished with status 'done' Installing backend dependencies: started Installing backend dependencies: still running... Installing backend dependencies: finished with status 'error' error: subprocess-exited-with-error × pip subprocess to install backend dependencies did not run successfully. │ exit code: 1 ╰─> [43 lines of output] Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/, https://wheels.home-assistant.io/musllinux-index/, https://wheels.home-assistant.io/musllinux-index/ Collecting patchelf>=0.11.0 Downloading patchelf-0.17.2.1-py2.py3-none-manylinux_2_17_armv7l.manylinux2014_armv7l.musllinux_1_1_armv7l.whl.metadata (3.3 kB) Collecting ninja>=1.8.2 Downloading ninja-1.11.1.1.tar.gz (132 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.4/132.4 kB 859.5 kB/s eta 0:00:00 Installing build dependencies: started Installing build dependencies: finished with status 'done' Getting requirements to build wheel: started Getting requirements to build wheel: finished with status 'done' Preparing metadata (pyproject.toml): started Preparing metadata (pyproject.toml): finished with status 'done' Downloading patchelf-0.17.2.1-py2.py3-none-manylinux_2_17_armv7l.manylinux2014_armv7l.musllinux_1_1_armv7l.whl (381 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.1/381.1 kB 570.6 kB/s eta 0:00:00 Building wheels for collected packages: ninja Building wheel for ninja (pyproject.toml): started Building wheel for ninja (pyproject.toml): finished with status 'error' error: subprocess-exited-with-error × Building wheel for ninja (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [15 lines of output] /tmp/pip-build-env-a7rf3bs2/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output warnings.warn("git archive did not support describe output") /tmp/pip-build-env-a7rf3bs2/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied) warnings.warn("unprocessed git archival found (no export subst applied)") Traceback (most recent call last): File "/tmp/pip-build-env-a7rf3bs2/overlay/lib/python3.12/site-packages/skbuild/setuptools_wrap.py", line 645, in setup cmkr = cmaker.CMaker(cmake_executable) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-a7rf3bs2/overlay/lib/python3.12/site-packages/skbuild/cmaker.py", line 148, in __init__ self.cmake_version = get_cmake_version(self.cmake_executable) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-a7rf3bs2/overlay/lib/python3.12/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version raise SKBuildError(msg) from err Problem with the CMake installation, aborting build. CMake executable is cmake [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for ninja Failed to build ninja ERROR: Could not build wheels for ninja, which is required to install pyproject.toml-based projects [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × pip subprocess to install backend dependencies did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × pip subprocess to install build dependencies did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by tmjo** [comment] 2024-04-08 21:54
Duplicate of #8 , see also [here](https://github.com/home-assistant/core/issues/111732).

**Closed by tmjo** 2024-04-08 21:54 UTC
